[bootstrap.hooks.pre-packages]
run = "mise run setup-dnf-repos"

[bootstrap.packages]
"dnf:1password" = "latest"
"dnf:1password-cli" = "latest"
"dnf:cmake" = "latest"
"dnf:fish" = "latest"
"dnf:gcc" = "latest"
"dnf:ghostty" = "latest"

[dotfiles]
"~/.config/mise/config.linux.toml" = "mise.linux.toml"
"~/.config/pi/auth.json" = { source = "pi/auth.linux.json", mode = "copy" }
"~/.config/pi/settings.json" = { source = "pi/settings.linux.json", mode = "copy" }
"~/.ssh/authorized_keys" = { source = "ssh/authorized_keys" }
