# change default prefix and unbind default
set -g prefix C-a
unbind C-b

# lower delay between prefix and command
set -s escape-time 1

# send C-a to other apps
bind C-a send-prefix

# splitting panes with | and -
bind | split-window -h
bind - split-window -v

# vim-like movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# mouse support - set on for mouse usage
set -g mouse off

# set default terminal mode to 256color
set -g default-terminal "screen-256color"
