# change default prefix and unbind default
set -g prefix C-a
unbind C-b

# lower delay between prefix and command
set -s escape-time 1

# send C-a to other apps
bind C-a send-prefix

# splitting panes with | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim settings
setw -g mode-keys vi
set-option -g status-keys vi

# vim-like movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# mouse support - set on for mouse usage
set -g mouse off

# set default terminal mode to 256color
set -g default-terminal "screen-256color"

# set the base index for windows to 1
set -g base-index 1

# set the base index for panes to 1
set -g pane-base-index 1

# center the window list
set -g status-justify centre

# smart pane switching with awareness of vim splits
# bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-h) || tmux select-pane -L"
# bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-j) || tmux select-pane -D"
# bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-k) || tmux select-pane -U"
# bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys C-l) || tmux select-pane -R"
# bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim$' && tmux send-keys 'C-\\') || tmux select-pane -l"
# bind C-l send-keys 'C-l'

# rebind copy and paste mode to be more vim-like
# unbind [
# bind Escape copy-mode
# unbind p
# bind p paste-buffer
# bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
# bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

